name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: xyzzylabs/setup-zig@v1
      - name: Check formatting
        run: zig fmt --check .
      - name: Run tests
        run: zig build test --summary all
